language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - nightly
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace -- --nocapture
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
